apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: terminus-op-storage-class
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: WaitForFirstConsumer